### ISSUE TITLE
SoGo 60.0.2 Corrupt Addon Thunderbird

### ISSUE THREAD

**Issue by kunalnagar** [inverse-inc/sogo-connector#6]
Thunderbird Version: 60.5.1 (64-bit)
Ubuntu 18.04.2

![image](https://user-images.githubusercontent.com/2741371/55107914-6fd74080-50f8-11e9-9320-aef8b1871973.png)

Error when installing SoGo Connector 60.0.2 from the [GitHub Releases page](https://github.com/inverse-inc/sogo-connector/releases)

![image](https://user-images.githubusercontent.com/2741371/55108037-b75dcc80-50f8-11e9-8f4b-4cb688d988ed.png)

**Comment by extrafu** [comment]
That's the source, not the XPI. Get the XPI from sogo.nu or compile it yourself.

**Comment by kunalnagar** [comment]
@extrafu thanks, that worked. I'm using Firefox and when you click on the XPI link to download, it tries to install it in Firefox and that also gives a corrupt warning. Had to wget to my Downloads directory and then drag it to the Thunderbird Add-ons page. Just in case anyone runs into a similar issue.
